djangotask1/about/urls.py
from django.urls import path
from about import views

app_name = 'about'

urlpatterns = [
    path('', views.description, name='description'),
]

djangotask1/catalog/urls.py
from django.urls import path, re_path
from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    re_path(r'^(?P<pk>[1-9][0-9]*?)/$', views.item_detail, name='item_detail'),
]

djangotask1/djangotask1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('homepage.urls')),
    path('catalog/', include('catalog.urls')),
    path('about/', include('about.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

djangotask1/homepage/urls.py
from django.urls import path
from homepage import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home')
]

djangotask1/about/models.py
# from django.db import models

# Create your models here.

djangotask1/catalog/models.py
from django.db import models
from django.utils.safestring import mark_safe
from sorl.thumbnail import get_thumbnail

from .validators import validate_desc, validate_slug, validate_weight


class Tag(models.Model):
    name = models.CharField(max_length=150, default='your name')
    is_published = models.BooleanField(default=True)
    slug = models.CharField(
        max_length=200, validators=[validate_slug], default='slug')


class Category(models.Model):
    is_published = models.BooleanField(default=True)
    name = models.CharField(max_length=150, default='your name')
    slug = models.CharField(
        max_length=200, validators=[validate_slug], default='slug')
    weight = models.IntegerField(default=100, validators=[validate_weight])


class Item(models.Model):
    is_published = models.BooleanField(default=True)
    is_on_main = models.BooleanField(default=False)
    name = models.CharField(max_length=150, default='your name')
    text = models.TextField(default='your desc', validators=[validate_desc])
    category = models.ForeignKey(
        'Category', on_delete=models.DO_NOTHING, null=True)
    images = models.ForeignKey(
        'DescriptionImages', on_delete=models.CASCADE, null=True)
    tags = models.ManyToManyField('Tag')

    class Meta:
        verbose_name = 'товар'
        verbose_name = 'товары'
        default_related_name = 'items'
        ordering = ('category__name',)

    upload = models.ImageField(upload_to='uploads/%Y/%m', default='nothing')

    @property
    def get_img(self):
        return get_thumbnail(self.upload, '300x300', crop='center', quality=51)

    def image_tmb(self):
        if self.upload:
            return mark_safe(
                f'<img src="{self.get_img.url}">'
            )
        return 'Нет изображения'

    image_tmb.short_description = 'превью'
    image_tmb.allow_tags = True


class DescriptionImages(models.Model):
    is_published = models.BooleanField(default=True)
    pictures = models.ImageField(upload_to='uploads/%Y/%m', default='nothing')

djangotask1/homepage/models.py
# from django.db import models

# Create your models here.

djangotask1/about/views.py
from django.shortcuts import render


def description(request):
    return render(request, 'about/index.html', {'navbar': 'about'})

djangotask1/catalog/views.py
from django.shortcuts import render
from catalog.models import Item
from django.shortcuts import get_object_or_404


def item_list(request):
    items = Item.objects.filter(is_published=True).order_by('category')
    context = {'items': items, 'navbar': 'catalog'}
    return render(request, 'catalog/index.html', context)


def item_detail(request, pk: int):
    item = get_object_or_404(Item, pk=pk)
    context = {'item': item, 'navbar': 'catalog'}
    return render(request, 'catalog/detail.html', context)

djangotask1/homepage/views.py
from django.shortcuts import render
from catalog.models import Item


def home(request):
    items = Item.objects.filter(is_published=True,
                                is_on_main=True).order_by('name')
    context = {'items': items, 'navbar': 'home'}
    return render(request, 'homepage/index.html', context)

djangotask1/templates/about/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>About</title>
  
</head>
<body>
  {% extends "base.html" %}
  {% load static %}
  {% block content %}
  <link rel="stylesheet" href="{% static 'css/about_style.css' %}">
  <p class="about-company">Мясо кота или кошки довольно калорийно, содержание белка в нем выше, чем в баранине,
    говядине, свинине и телятине, однако холестерина в этом мясе меньше,
    чем практически в любом другом продукте животного происхождения. И жира тоже меньше,
    а усваивается этот жир лучше...</p>
  {% endblock %}
</body>
</html>

djangotask1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Л4 Задача №1</title>
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'ico/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'ico/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'ico/favicon-16x16.png' %}">
        <link rel="mask-icon" href="{% static 'ico/safari-pinned-tab.svg' %}" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </head>
    <body>
        {% include "includes/header.html" %}
        <main>
            {% block content %}{% endblock %}
        </main>
        {% include "includes/footer.html" %}
    </body>
</html>

djangotask1/templates/catalog/detail.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Item</title>
</head>
<body>
  {% extends "base.html" %}
  {% load static %}
  {% block content %}
  <link rel="stylesheet" href="{% static 'css/catalog_detail_style.css' %}">
  <div class="whole_card">
    <h2>{{ item.name }}</h2>
    <h4>Тэги: {% for tag in item.tags.all %} {{ tag.name }} {% endfor %}</h4>
    <img src="{{ item.get_img.url }}" alt="">
    <p>Описание: {{ item.text }}</p>
  </div>
  {% endblock %}
</body>
</html>

djangotask1/templates/catalog/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Catalog</title>
</head>
<body>
  {% extends "base.html" %}
  {% load static %}
  {% block content %}
  <link rel="stylesheet" href="{% static 'css/catalog_style.css' %}">
  {% include "includes/small_item_detail.html" %}
  {% endblock %}
</body>
</html>

djangotask1/templates/homepage/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Homepage</title>
</head>
<body>
  {% extends "base.html" %}
  {% load static %}
  {% block content %}
  <link rel="stylesheet" href="{% static 'css/homepage_style.css' %}">
  <h1 class="big_title">МММ КАКОЙ ВКУСНЫЙ ШАШЛЫК...</h1>
  {% include "includes/small_item_detail.html" %}
  {% endblock %}
</body>
</html>

djangotask1/templates/includes/footer.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Подвал</title>
</head>
<body>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/footer_style.css' %}">
  <footer>
    <p> И. И. Иванов, 2010
        Иванов И. И., 2010—2015
        ООО "Правообладатель контента", 2010—2007
        Иванов И. И., перевод на русский язык, 2045
        2010—2007 Правообладатель контента</p>
  </footer>
</body>
</html>

djangotask1/templates/includes/header.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Навигация</title>
</head>
<body>
  {% load static %}
  <link href="{% static 'css/header_style.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <header>
    {% block navbar-content %}
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">L4task1</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
                {% block nav-home %}<a class="nav-item nav-link {% if navbar == 'home' %} active {% endif %}" href="{% url 'homepage:home' %}">На главную</a>{% endblock %}
                {% block nav-catalog %}<a class="nav-item nav-link {% if navbar == 'catalog' %} active {% endif %}" href="{% url 'catalog:item_list' %}">Список товаров</a>{% endblock %}
                {% block nav-about %}<a class="nav-item nav-link {% if navbar == 'about' %} active {% endif %}" href="{% url 'about:description' %}">О проекте</a>{% endblock %}
          </div>
        </div>
      </nav>
    {% endblock navbar-content %}
</header>
</body>
</html>

djangotask1/templates/includes/small_item_detail.html
<!DOCTYPE html>
<meta charset="UTF-8">
{% load static %}
<link rel="stylesheet" href="{% static 'css/small_item_detail.css' %}">
<div class="item_preview">
{% for item in items %}
  <a href="{% url 'catalog:item_detail' item.id %}"><h2>{{ item.name }}</h2></a>
  <h4>Категория: {{ item.category.name }} /// Тэги: {% for tag in item.tags.all %} {{ tag.name }} {% endfor %}</h4>
  <p>Описание: {{ item.text|truncatewords:10 }}</p>
{% endfor %}
</div>